server:
  port: 80
spring:
  thymeleaf:
    cache: false
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 5MB
logging:
  level:
    root: WARN
    org.springframework:
      root: TRACE
    com.github.dockerjava: WARN
    org.testcontainers: INFO