CREATE TABLE IF NOT EXISTS need
(
    id   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type CHAR(50)        NOT NULL
);

CREATE TABLE IF NOT EXISTS volunteer
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS need_type
(
    id char(50) NOT NULL PRIMARY KEY
);
